# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
