# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
